
name = "dashboard-backend"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "dashboard-db"
database_id = "fb36239a-9ca1-4de0-b006-df7f04a0c85b"
